---
version: "3.3"
services:
  personal-website:
    container_name: personal-website
    image: '{{ item.image }}'
    networks:
      proxy:
        ipv4_address: 172.24.0.9
    ports:
      - 82:80
    restart: unless-stopped

networks:
  proxy:
    external: true